/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class GestorBiblioteca extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public GestorBiblioteca() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAgregarLibro = new javax.swing.JButton();
        jButtonEliminarLibro = new javax.swing.JButton();
        jButtonAutores = new javax.swing.JButton();
        jButtonEditorial = new javax.swing.JButton();
        jButtonCategoria = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonUsuario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonMostrarLibros = new javax.swing.JButton();
        jButtonMostrarAutores = new javax.swing.JButton();
        jButtonMostrarEditorial = new javax.swing.JButton();
        jButtonMostrarCategorias = new javax.swing.JButton();
        jButtonMostrarUsuarios = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButtonAutores1 = new javax.swing.JButton();
        jButtonEdicion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAgregarLibro = new javax.swing.JMenuItem();
        jMenuItemEliminarLibro = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAgregarAutor = new javax.swing.JMenuItem();
        jMenuItemEliminarAutores = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAgregarEditorial = new javax.swing.JMenuItem();
        jMenuItemEliminarEditorial = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAgregarCategoria = new javax.swing.JMenuItem();
        jMenuItemEliminarCategoria = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAgregarUsuario = new javax.swing.JMenuItem();
        jMenuItemEliminarUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonAgregarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/libro principal.png"))); // NOI18N
        jButtonAgregarLibro.setText("<html><p>Agregar</p><center>ejemplar</center></html>");
        jButtonAgregarLibro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAgregarLibro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarLibroActionPerformed(evt);
            }
        });

        jButtonEliminarLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/eliminar libro principal.png"))); // NOI18N
        jButtonEliminarLibro.setText("<html><p>Eliminar</p><center>ejemplar</center></html>");
        jButtonEliminarLibro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEliminarLibro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarLibroActionPerformed(evt);
            }
        });

        jButtonAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/autores normal.png"))); // NOI18N
        jButtonAutores.setText("<html><p>Autores</p></html>");
        jButtonAutores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAutores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutoresActionPerformed(evt);
            }
        });

        jButtonEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/editorial - copia.png"))); // NOI18N
        jButtonEditorial.setText("<html><p>Editorial</p></html>");
        jButtonEditorial.setToolTipText("");
        jButtonEditorial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditorial.setIconTextGap(5);
        jButtonEditorial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditorialActionPerformed(evt);
            }
        });

        jButtonCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/categoria original.png"))); // NOI18N
        jButtonCategoria.setText("<html><p>Categorias</p></html>");
        jButtonCategoria.setToolTipText("");
        jButtonCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButtonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/usuario original.png"))); // NOI18N
        jButtonUsuario.setText("<html><p>Usuarios</p></html>");
        jButtonUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jButtonMostrarLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/libros.png"))); // NOI18N

        jButtonMostrarAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/autores.png"))); // NOI18N

        jButtonMostrarEditorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/editorial.png"))); // NOI18N

        jButtonMostrarCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/categoria.png"))); // NOI18N

        jButtonMostrarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/usuario.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonMostrarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMostrarAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMostrarEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMostrarCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMostrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonMostrarAutores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMostrarEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMostrarCategorias)
                    .addComponent(jButtonMostrarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonMostrarLibros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonAutores1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/libro original.png"))); // NOI18N
        jButtonAutores1.setText("<html><p>Libro</p></html>");
        jButtonAutores1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAutores1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAutores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutores1ActionPerformed(evt);
            }
        });

        jButtonEdicion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/edision original.png"))); // NOI18N
        jButtonEdicion.setText("<html><p>Edición</p></html>");
        jButtonEdicion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEdicion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEdicionActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo ");

        jMenuItemAgregarLibro.setText("Agregar/Modificar Libro");
        jMenuItemAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarLibroActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAgregarLibro);

        jMenuItemEliminarLibro.setText("Eliminar Libro");
        jMenu1.add(jMenuItemEliminarLibro);
        jMenu1.add(jSeparator2);

        jMenuItemAgregarAutor.setText("Agregar/Modificar Autores");
        jMenuItemAgregarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarAutorActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAgregarAutor);

        jMenuItemEliminarAutores.setText("Eliminar Autores");
        jMenu1.add(jMenuItemEliminarAutores);
        jMenu1.add(jSeparator3);

        jMenuItemAgregarEditorial.setText("Agregar/Modificar Editorial");
        jMenuItemAgregarEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarEditorialActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAgregarEditorial);

        jMenuItemEliminarEditorial.setText("Eliminar Editorial");
        jMenu1.add(jMenuItemEliminarEditorial);
        jMenu1.add(jSeparator4);

        jMenuItemAgregarCategoria.setText("Agregar/Modificar Categoria");
        jMenuItemAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAgregarCategoria);

        jMenuItemEliminarCategoria.setText("Eliminar Categoria");
        jMenu1.add(jMenuItemEliminarCategoria);
        jMenu1.add(jSeparator5);

        jMenuItemAgregarUsuario.setText("Agregar/Modificar Usuario");
        jMenuItemAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAgregarUsuario);

        jMenuItemEliminarUsuario.setText("Eliminar Usuario");
        jMenu1.add(jMenuItemEliminarUsuario);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAgregarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAutores1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonEdicion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEliminarLibro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAgregarLibro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAutores, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditorial, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCategoria, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAutores1))
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jButtonEditorial.getAccessibleContext().setAccessibleName("<html><p>/n/n</p><p>Editorial</p></html>");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarLibroActionPerformed
        new Ejemplar().setVisible(true);
    }//GEN-LAST:event_jButtonAgregarLibroActionPerformed

    private void jButtonAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutoresActionPerformed
        new Autor().setVisible(true);
    }//GEN-LAST:event_jButtonAutoresActionPerformed

    private void jButtonEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarLibroActionPerformed
        new Eliminar().setVisible(true);
    }//GEN-LAST:event_jButtonEliminarLibroActionPerformed

    private void jMenuItemAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarLibroActionPerformed
        new Libro().setVisible(true);
    }//GEN-LAST:event_jMenuItemAgregarLibroActionPerformed

    private void jButtonAutores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutores1ActionPerformed
        new Libro().setVisible(true);
    }//GEN-LAST:event_jButtonAutores1ActionPerformed

    private void jButtonEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEdicionActionPerformed
        new Edicion().setVisible(true);
    }//GEN-LAST:event_jButtonEdicionActionPerformed

    private void jButtonEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditorialActionPerformed
        new Edicion().setVisible(true);
    }//GEN-LAST:event_jButtonEditorialActionPerformed

    private void jButtonCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaActionPerformed
        new Categoria().setVisible(true);
    }//GEN-LAST:event_jButtonCategoriaActionPerformed

    private void jButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioActionPerformed
        new USUARIO().setVisible(true);
    }//GEN-LAST:event_jButtonUsuarioActionPerformed

    private void jMenuItemAgregarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarAutorActionPerformed
        new Autor().setVisible(true);
    }//GEN-LAST:event_jMenuItemAgregarAutorActionPerformed

    private void jMenuItemAgregarEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarEditorialActionPerformed
        new Edicion().setVisible(true);
    }//GEN-LAST:event_jMenuItemAgregarEditorialActionPerformed

    private void jMenuItemAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarCategoriaActionPerformed
        new Categoria().setVisible(true);
    }//GEN-LAST:event_jMenuItemAgregarCategoriaActionPerformed

    private void jMenuItemAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarUsuarioActionPerformed
        new USUARIO().setVisible(true);
    }//GEN-LAST:event_jMenuItemAgregarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestorBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestorBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestorBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestorBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestorBiblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarLibro;
    private javax.swing.JButton jButtonAutores;
    private javax.swing.JButton jButtonAutores1;
    private javax.swing.JButton jButtonCategoria;
    private javax.swing.JButton jButtonEdicion;
    private javax.swing.JButton jButtonEditorial;
    private javax.swing.JButton jButtonEliminarLibro;
    private javax.swing.JButton jButtonMostrarAutores;
    private javax.swing.JButton jButtonMostrarCategorias;
    private javax.swing.JButton jButtonMostrarEditorial;
    private javax.swing.JButton jButtonMostrarLibros;
    private javax.swing.JButton jButtonMostrarUsuarios;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAgregarAutor;
    private javax.swing.JMenuItem jMenuItemAgregarCategoria;
    private javax.swing.JMenuItem jMenuItemAgregarEditorial;
    private javax.swing.JMenuItem jMenuItemAgregarLibro;
    private javax.swing.JMenuItem jMenuItemAgregarUsuario;
    private javax.swing.JMenuItem jMenuItemEliminarAutores;
    private javax.swing.JMenuItem jMenuItemEliminarCategoria;
    private javax.swing.JMenuItem jMenuItemEliminarEditorial;
    private javax.swing.JMenuItem jMenuItemEliminarLibro;
    private javax.swing.JMenuItem jMenuItemEliminarUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
