/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Negocio.NEGOCIO_OBJETOS;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class PedirEjemplar extends javax.swing.JFrame {
    
    ArrayList<ArrayList<String>> registroUsuario;
    ArrayList<String> nombretablaUsuario;
    ArrayList<String> attSeleccionadoUsuario;
    ArrayList<String> condicioneUsuario;
    
    //Libros
    ArrayList<ArrayList<String>> registrolibros;
    ArrayList<String> nombretablaslibros;
    ArrayList<String> attSeleccionadoslibros;
    int elemento_seleccionado1=0;
    String IdLibro="";
    
    //Ediciones
    ArrayList<ArrayList<String>> registro2;
    ArrayList<String> nombretablas2;
    ArrayList<String> attSeleccionados2;
    ArrayList<String> condiciones;
    int elemento_seleccionado2=0;
    String IdEdicion="";
    
    //Ejemplar
    ArrayList<ArrayList<String>> registros3;
    ArrayList<String> nombretablas3;
    ArrayList<String> attSeleccionados3;
    ArrayList<String> condiciones3;
    int elemento_seleccionado3=0;
    String IdEjemplar="";
    
    //modificar ejemplar
    ArrayList<ArrayList<String>> registroEjemplar;
    ArrayList<String> nombretablaEjemplar;
    ArrayList<String> condicioneEjemplar;
    ArrayList<String> wherecondicioneEjemplar;
    
    
    
    /**
     * Creates new form PedirEjemplar
     */
    public PedirEjemplar() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextFieldNombre.setEnabled(false);
        this.buttonGroup1.add(jRadioButtonDisponible);
        this.buttonGroup1.add(jRadioButtonNoDisponible);
        this.jRadioButtonNoDisponible.setSelected(true);
        try {
            registrolibros = new ArrayList();
            nombretablaslibros = new ArrayList();
            attSeleccionadoslibros = new ArrayList();
            nombretablaslibros.add("LIBRO");
            attSeleccionadoslibros.add("ID_LIBRO");
            attSeleccionadoslibros.add("NOMBRE");
            registrolibros = (ArrayList<ArrayList<String>>) NEGOCIO_OBJETOS.getInstance().obtenerRegistros(nombretablaslibros, this.attSeleccionadoslibros,null,null,null);
            System.out.println(registrolibros.toString());
            for(int i = 1; i<registrolibros.size(); i++){
                 this.jComboBoxLibro.addItem(registrolibros.get(i).get(1));
            }
            // Cargar los datos en el primer combo box
            
           //Cargar los datos en el segundo combo box
           
        } catch (Exception ex) {
            Logger.getLogger(Edicion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //registroEjemplar = new ArrayList();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateChooserPrestamo = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDiasPrestamo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonDisponible = new javax.swing.JRadioButton();
        jRadioButtonNoDisponible = new javax.swing.JRadioButton();
        jButtonAceptar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxLibro = new javax.swing.JComboBox<>();
        jComboBoxEdicion = new javax.swing.JComboBox<>();
        jComboBoxEjemplar = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icono prestamo.jpg"))); // NOI18N

        jLabel2.setText("Cedula");

        jLabel3.setText("Nombre");

        jLabel4.setText("Fecha de prestamo");

        jLabel5.setText("Dias de prestamo");

        jLabel7.setText("Estado");

        jRadioButtonDisponible.setText("Disponible");

        jRadioButtonNoDisponible.setText("No disponible");

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLabel8.setText("Libro");

        jLabel9.setText("Edicion");

        jLabel10.setText("Ejemplar");

        jComboBoxLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLibroActionPerformed(evt);
            }
        });

        jComboBoxEdicion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxEdicionMouseClicked(evt);
            }
        });
        jComboBoxEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEdicionActionPerformed(evt);
            }
        });

        jComboBoxEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEjemplarActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCedula)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jComboBoxLibro, 0, 151, Short.MAX_VALUE)
                            .addComponent(jComboBoxEdicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxEjemplar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar))
                    .addComponent(jDateChooserPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDiasPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonDisponible)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonNoDisponible)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBoxLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBoxEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDiasPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDisponible)
                    .addComponent(jLabel7)
                    .addComponent(jRadioButtonNoDisponible))
                .addGap(6, 6, 6)
                .addComponent(jButtonAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLibroActionPerformed
        elemento_seleccionado1=jComboBoxLibro.getSelectedIndex();
        IdLibro=registrolibros.get(elemento_seleccionado1+1).get(0);
        System.out.println("\n\n\n------------Id del libro-----------\n");
        System.out.println("ID del libro: " + IdLibro);
        jComboBoxEdicion.removeAllItems();
        elemento_seleccionado2=0;
        try {
            registro2 = new ArrayList();
            nombretablas2 = new ArrayList();
            attSeleccionados2 = new ArrayList();
            condiciones = new ArrayList();
            nombretablas2.add("EDISION");
            attSeleccionados2.add("ID_EDISION");
            attSeleccionados2.add("ANIO");
            System.out.println("------------------------ingreso aqui-------------------------");
            System.out.println(IdLibro);
            condiciones.add("ID_LIBRO = '"+IdLibro+"'");
            registro2 = (ArrayList<ArrayList<String>>) NEGOCIO_OBJETOS.getInstance().obtenerRegistros(nombretablas2, this.attSeleccionados2,this.condiciones,null,null);
            System.out.println(registro2.toString());
            for(int i = 1; i<registro2.size(); i++){
                 this.jComboBoxEdicion.addItem(registro2.get(i).get(1));
             }
        } 
        catch (Exception ex) {
            Logger.getLogger(Edicion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jComboBoxLibroActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            String cedula = jTextFieldCedula.getText();
            registroUsuario = new ArrayList();
            nombretablaUsuario = new ArrayList();
            attSeleccionadoUsuario = new ArrayList();
            condicioneUsuario = new ArrayList();
            nombretablaUsuario.add("USUARIO");
            attSeleccionadoUsuario.add("ID_USUARIO");
            attSeleccionadoUsuario.add("NOMBRE");
            condicioneUsuario.add("ID_USUARIO = '"+cedula+"'");
            registroUsuario = (ArrayList<ArrayList<String>>) NEGOCIO_OBJETOS.getInstance().obtenerRegistros(nombretablaUsuario, this.attSeleccionadoUsuario,condicioneUsuario,null,null);
            System.out.println("Resultado obtenido:---------------");
            System.out.println(registroUsuario.size());
            if(registroUsuario.size()==1){
                JOptionPane.showMessageDialog(null, "El usuario no esta registrado");
            }
            else{
                String nombre=registroUsuario.get(1).get(1);
                this.jTextFieldNombre.setText(nombre);
                System.out.println("nobre del usuario: "+nombre);
            }
        } catch (Exception ex) {
            Logger.getLogger(PedirEjemplar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jComboBoxEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEdicionActionPerformed
//        elemento_seleccionado2=(jComboBoxEdicion.getSelectedIndex())+1;
//        System.out.println("*************************** ELemento seleccionado: "+elemento_seleccionado2);
//        IdEdicion=registro2.get(elemento_seleccionado2).get(0);
//        elemento_seleccionado3=0;
//        this.jComboBoxEjemplar.removeAllItems();
//        System.out.println("id de la edision:"+IdEdicion);
//        try{
//            registros3 = new ArrayList();
//            nombretablas3 = new ArrayList();
//            attSeleccionados3 = new ArrayList();
//            condiciones3 = new ArrayList();
//            nombretablas3.add("EJEMPLAR");
//            attSeleccionados3.add("ID_EJEMPLAR");
//            System.out.println("**********************************************************************");
//            condiciones3.add("ID_EDISION = '"+ IdEdicion+ "' and ID_LIBRO= '"+IdLibro+"'");
//            registros3 = (ArrayList<ArrayList<String>>) NEGOCIO_OBJETOS.getInstance().obtenerRegistros(nombretablas3, this.attSeleccionados3,this.condiciones3,null,null);
//            
//            System.out.println("los registros//"+registros3);
//            for(int i = 1; i<registros3.size(); i++){
//                 this.jComboBoxEjemplar.addItem(registros3.get(i).get(0));
//            }
//        }
//        catch (Exception ex) {
//            Logger.getLogger(Edicion.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jComboBoxEdicionActionPerformed

    private void jComboBoxEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEjemplarActionPerformed
        // obtencion del id de ejemplar
        elemento_seleccionado3 = jComboBoxEjemplar.getSelectedIndex();
        IdEjemplar=registros3.get(elemento_seleccionado3+1).get(0);
        System.out.println("Id Ejemplar: "+IdEjemplar);
        
    }//GEN-LAST:event_jComboBoxEjemplarActionPerformed

    private void jComboBoxEdicionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxEdicionMouseClicked
        //evento mous clicked del combo edision
        elemento_seleccionado2=(jComboBoxEdicion.getSelectedIndex())+1;
        System.out.println("*************************** ELemento seleccionado: "+elemento_seleccionado2);
        IdEdicion=registro2.get(elemento_seleccionado2).get(0);
        elemento_seleccionado3=0;
        this.jComboBoxEjemplar.removeAllItems();
        System.out.println("id de la edision:"+IdEdicion);
        try{
            registros3 = new ArrayList();
            nombretablas3 = new ArrayList();
            attSeleccionados3 = new ArrayList();
            condiciones3 = new ArrayList();
            nombretablas3.add("EJEMPLAR");
            attSeleccionados3.add("ID_EJEMPLAR");
            System.out.println("**********************************************************************");
            condiciones3.add("ID_EDISION = '"+ IdEdicion+ "' and ID_LIBRO= '"+IdLibro+"' and ESTADO!= '1'");
            registros3 = (ArrayList<ArrayList<String>>) NEGOCIO_OBJETOS.getInstance().obtenerRegistros(nombretablas3, this.attSeleccionados3,this.condiciones3,null,null);
            
            System.out.println("los registros//"+registros3);
            for(int i = 1; i<registros3.size(); i++){
                 this.jComboBoxEjemplar.addItem(registros3.get(i).get(0));
            }
            
        }
        catch (Exception ex) {
            Logger.getLogger(Edicion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_jComboBoxEdicionMouseClicked

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        try {
            Date fecha_prestamo = jDateChooserPrestamo.getDate();
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
            String FECHA_PRESTAMO = df.format(fecha_prestamo);
            String ID_USUARIO = this.jTextFieldCedula.getText();
            String ID_LIBRO = IdLibro;
            String ID_EDISION=IdEdicion;
            String ID_EJEMPLAR=IdEjemplar;
            String ESTADO = "0";
            String NUMERO_DIAS_PRESTAMO = jTextFieldDiasPrestamo.getText();
            String FECHA_DEVOLUCION = "";
            //int ID_USUARIO, int ID_EJEMPLAR, int ID_EDISION, int ID_LIBRO, String ESTADO, int NUMERO_DIAS_PRESTAMO, String FECHA_PRESTAMO, String FECHA_DEVOLIUCION
            String[] args = {"PEDIR_EJEMPLAR",ID_USUARIO,ID_EJEMPLAR,ID_EDISION,ID_LIBRO,ESTADO,NUMERO_DIAS_PRESTAMO,FECHA_PRESTAMO,FECHA_DEVOLUCION};
            NEGOCIO_OBJETOS.getInstance().insertarRegistro(args);
            JOptionPane.showMessageDialog(rootPane,"Se ha creado el Ejemplar satisfactoriamente.","Enhorabuena",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(PedirEjemplar.class.getName()).log(Level.SEVERE, null, ex);
        }
        nombretablaEjemplar = new ArrayList();
        condicioneEjemplar = new ArrayList();
        wherecondicioneEjemplar = new ArrayList();
        nombretablaEjemplar.add("EJEMPLAR");
        condicioneEjemplar.add("ESTADO = '1'");
        wherecondicioneEjemplar.add("ID_EJEMPLAR= '"+IdEjemplar+"' AND ID_LIBRO= '"+IdLibro+"' AND ID_EDISION= '"+IdEdicion+"'");
        
        try {
            
            NEGOCIO_OBJETOS.getInstance().actualizarCampos(nombretablaEjemplar, condicioneEjemplar, wherecondicioneEjemplar);
            JOptionPane.showMessageDialog(rootPane, "Se ha actualizado correctamente");
            
           ///
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedirEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedirEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedirEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedirEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedirEjemplar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBoxEdicion;
    private javax.swing.JComboBox<String> jComboBoxEjemplar;
    private javax.swing.JComboBox<String> jComboBoxLibro;
    private com.toedter.calendar.JDateChooser jDateChooserPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonDisponible;
    private javax.swing.JRadioButton jRadioButtonNoDisponible;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldDiasPrestamo;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
