/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Negocio.NEGOCIO_OBJETOS;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class PedirEjemplar extends javax.swing.JFrame {
    
    ArrayList<ArrayList<String>> registroUsuario;
    ArrayList<String> nombretablaUsuario;
    ArrayList<String> attSeleccionadoUsuario;
    ArrayList<String> condicioneUsuario;
    
    //Libros
    ArrayList<ArrayList<String>> registrolibros;
    ArrayList<String> nombretablaslibros;
    ArrayList<String> attSeleccionadoslibros;
    int elemento_seleccionado1=0;
    String IdLibro="";
    
    //Ediciones
    ArrayList<ArrayList<String>> registro2;
    ArrayList<String> nombretablas2;
    ArrayList<String> attSeleccionados2;
    ArrayList<String> condiciones;
    int elemento_seleccionado2=0;
    String IdEdicion="";
    
    //Ejemplar
    ArrayList<ArrayList<String>> registroEemplar;
    ArrayList<String> nombretablaEjemplar;
    ArrayList<String> attSeleccionadoEjemplar;
    ArrayList<String> condicionesEjemplar;
    int elemento_seleccionado3=0;
    String IdEjemplar="";
    
    /**
     * Creates new form PedirEjemplar
     */
    public PedirEjemplar() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTextFieldNombre.setEnabled(false);
        try {
            registrolibros = new ArrayList();
            nombretablaslibros = new ArrayList();
            attSeleccionadoslibros = new ArrayList();
            nombretablaslibros.add("LIBRO");
            attSeleccionadoslibros.add("ID_LIBRO");
            attSeleccionadoslibros.add("NOMBRE");
            registrolibros = (ArrayList<ArrayList<String>>) NEGOCIO_OBJETOS.getInstance().obtenerRegistros(nombretablaslibros, this.attSeleccionadoslibros,null,null,null);
            System.out.println(registrolibros.toString());
            for(int i = 1; i<registrolibros.size(); i++){
                 this.jComboBoxLibro.addItem(registrolibros.get(i).get(1));
            }
            // Cargar los datos en el primer combo box
            
           //Cargar los datos en el segundo combo box
           
        } catch (Exception ex) {
            Logger.getLogger(Edicion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jDateChooserPrestamo = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDiasPrestamo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jDateChooserDevolucion = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jRadioButtonDisponible = new javax.swing.JRadioButton();
        jRadioButtonNoDisponible = new javax.swing.JRadioButton();
        jButtoBuscar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxLibro = new javax.swing.JComboBox<>();
        jComboBoxEdicion = new javax.swing.JComboBox<>();
        jComboBoxEjemplar = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/icono prestamo.jpg"))); // NOI18N

        jLabel2.setText("Cedula");

        jLabel3.setText("Nombre");

        jLabel4.setText("Fecha de prestamo");

        jLabel5.setText("Dias de prestamo");

        jLabel6.setText("Fecha de devolucion");

        jLabel7.setText("Estado");

        jRadioButtonDisponible.setText("Disponible");

        jRadioButtonNoDisponible.setText("No disponible");

        jButtoBuscar.setText("Buscar");

        jButtonAceptar.setText("Aceptar");

        jLabel8.setText("Libro");

        jLabel9.setText("Edicion");

        jLabel10.setText("Ejemplar");

        jComboBoxLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLibroActionPerformed(evt);
            }
        });

        jComboBoxEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEdicionActionPerformed(evt);
            }
        });

        jComboBoxEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEjemplarActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCedula)
                    .addComponent(jTextFieldNombre)
                    .addComponent(jComboBoxLibro, 0, 151, Short.MAX_VALUE)
                    .addComponent(jComboBoxEdicion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxEjemplar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldDiasPrestamo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jDateChooserPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jDateChooserDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(39, 39, 39))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonDisponible)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonNoDisponible)))))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtoBuscar)
                        .addGap(16, 16, 16)
                        .addComponent(jButtonAceptar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBoxLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxEdicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBoxEjemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooserPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDiasPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooserDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDisponible)
                    .addComponent(jLabel7)
                    .addComponent(jRadioButtonNoDisponible))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoBuscar)
                    .addComponent(jButtonAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLibroActionPerformed
       /* elemento_seleccionado1=jComboBoxLibro.getSelectedIndex();
        IdLibro=registrolibros.get(elemento_seleccionado1+1).get(0);
        System.out.println("\n\n\n------------Id del libro-----------\n");
        System.out.println("ID del libro: " + IdLibro);
        jComboBoxEdicion.removeAllItems();
        elemento_seleccionado2=0;
        try {
            registro2 = new ArrayList();
            nombretablas2 = new ArrayList();
            attSeleccionados2 = new ArrayList();
            condiciones = new ArrayList();
            nombretablas2.add("EDISION");
            attSeleccionados2.add("ID_EDISION");
            attSeleccionados2.add("ANIO");
            System.out.println("------------------------ingreso aqui-------------------------");
            System.out.println(IdLibro);
            condiciones.add("ID_LIBRO = "+IdLibro);
            registro2 = (ArrayList<ArrayList<String>>) NEGOCIO_OBJETOS.getInstance().obtenerRegistros(nombretablas2, this.attSeleccionados2,this.condiciones,null,null);
            System.out.println(registro2.toString());
            for(int i = 1; i<registro2.size(); i++){
                 this.jComboBoxEdicion.addItem(registro2.get(i).get(1));
             }
        } 
        catch (Exception ex) {
            Logger.getLogger(Edicion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        */
    }//GEN-LAST:event_jComboBoxLibroActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            String cedula = jTextFieldCedula.getText();
            registroUsuario = new ArrayList();
            nombretablaUsuario = new ArrayList();
            attSeleccionadoUsuario = new ArrayList();
            condicioneUsuario = new ArrayList();
            nombretablaUsuario.add("USUARIO");
            attSeleccionadoUsuario.add("ID_USUARIO");
            attSeleccionadoUsuario.add("NOMBRE");
            condicioneUsuario.add("ID_USUARIO = '"+cedula+"'");
            registroUsuario = (ArrayList<ArrayList<String>>) NEGOCIO_OBJETOS.getInstance().obtenerRegistros(nombretablaUsuario, this.attSeleccionadoUsuario,condicioneUsuario,null,null);
            System.out.println("Resultado obtenido:---------------");
            System.out.println(registroUsuario.size());
            if(registroUsuario.size()==1){
                JOptionPane.showMessageDialog(null, "El usuario no esta registrado");
            }
            else{
                String nombre=registroUsuario.get(1).get(1);
                this.jTextFieldNombre.setText(nombre);
                System.out.println("nobre del usuario: "+nombre);
            }
        } catch (Exception ex) {
            Logger.getLogger(PedirEjemplar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jComboBoxEdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEdicionActionPerformed
        /*elemento_seleccionado2=jComboBoxEdicion.getSelectedIndex();
        IdEdicion=registro2.get(elemento_seleccionado2+1).get(0);
        System.out.println("ID del Edicion: " + IdEdicion);
        elemento_seleccionado3=0;
        try {
            registroEemplar = new ArrayList();
            nombretablaEjemplar = new ArrayList();
            attSeleccionadoEjemplar = new ArrayList();
            condicionesEjemplar = new ArrayList();
            nombretablaEjemplar.add("EJEMPLAR");
            attSeleccionadoEjemplar.add("ID_EJEMPLAR");
            System.out.println("------------------------ingreso aqui-------------------------");
            System.out.println(IdEjemplar);
            condicionesEjemplar.add("ID_EDISION = '"+IdEdicion+"'");
            registro2 = (ArrayList<ArrayList<String>>) NEGOCIO_OBJETOS.getInstance().obtenerRegistros(nombretablas2, this.attSeleccionados2,this.condicionesEjemplar,null,null);
            System.out.println(registro2.toString());
            for(int i = 1; i<registro2.size(); i++){
                 this.jComboBoxEdicion.addItem(registro2.get(i).get(1));
             }
        } 
        catch (Exception ex) {
            Logger.getLogger(Edicion.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }//GEN-LAST:event_jComboBoxEdicionActionPerformed

    private void jComboBoxEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEjemplarActionPerformed
        // obtencion del id de ejemplar
        
        
    }//GEN-LAST:event_jComboBoxEjemplarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedirEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedirEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedirEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedirEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedirEjemplar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtoBuscar;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBoxEdicion;
    private javax.swing.JComboBox<String> jComboBoxEjemplar;
    private javax.swing.JComboBox<String> jComboBoxLibro;
    private com.toedter.calendar.JDateChooser jDateChooserDevolucion;
    private com.toedter.calendar.JDateChooser jDateChooserPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonDisponible;
    private javax.swing.JRadioButton jRadioButtonNoDisponible;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldDiasPrestamo;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
