                        /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Negocio.NEGOCIO_OBJETOS;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Usuario
 */
public class Select extends javax.swing.JFrame {

    /**
     * Creates new form Select
     * <> Inicialisacion De Arraylist para los Atributos , 
    *  Las condiciones (en la calusula where), funciones de agregacion
     */
    
     ArrayList<String> attSeleccionados;
    ArrayList<String> condSeleccionados;
    ArrayList<String> condSeleccionados1;
    ArrayList <String> funciones;
    
    public Select() {
        initComponents();
        attSeleccionados = new ArrayList();
        condSeleccionados = new ArrayList();
        condSeleccionados1 = new ArrayList();
        funciones = new ArrayList();
        this.jButtonAgregarAtributos.setEnabled(false);
        this.jButtonEliminarAtributos.setEnabled(false);
        this.jButtonAceptar.setVisible(false);
        this.jComboBoxCondicion.setEnabled(false);
        this.setLocationRelativeTo(null);
        try {
             
              /**
                * Se carga los datos con los nombres delas 
                * tablas de la base de datos en <String> nombres
                * 
                */
            
             ArrayList<String> nombres  = NEGOCIO_OBJETOS.getInstance().getNombresTablas();
             
             for(int i = 0; i<nombres.size(); i++){
                 this.jComboBoxTabla.addItem(nombres.get(i));
             }
         } catch (Exception ex) {
             Logger.getLogger(Select.class.getName()).log(Level.SEVERE, null, ex);
         }// hasta aqui se concluye
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxOperacion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTabla = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxAtributo = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxOperador = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jButtonAgregarAtributos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonEliminarAtributos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonAgregarConsultas = new javax.swing.JButton();
        jButtonEliminarConsultas = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxAtributosOrdenar = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jRadioButtonAsendente = new javax.swing.JRadioButton();
        jRadioButtonDesendente = new javax.swing.JRadioButton();
        jRadioButtonNinguno = new javax.swing.JRadioButton();
        jButtonAceptar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButtonAgregarCondiciones = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxCondicion = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        listCondicionCon = new javax.swing.JList<>();
        jScrollPaneMuestraTabla = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("1. Especifique la operacion");

        jComboBoxOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        jComboBoxOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOperacionActionPerformed(evt);
            }
        });

        jLabel2.setText("2. Seleccione la tabla");

        jComboBoxTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTablaActionPerformed(evt);
            }
        });

        jLabel3.setText("3. Atributo condicional");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setText("4. Operador");

        jComboBoxOperador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">", "LIKE" }));

        jLabel5.setText("5. Valor");

        jScrollPane1.setViewportView(jList1);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButtonAgregarAtributos.setText("Agregar");
        jButtonAgregarAtributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarAtributosActionPerformed(evt);
            }
        });

        jLabel6.setText("Atributos de la tabla");

        jButtonEliminarAtributos.setText("Eliminar");
        jButtonEliminarAtributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarAtributosActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList2);

        jLabel7.setText("Atributos seleccionados");

        jLabel8.setText("Consultas");

        jButtonAgregarConsultas.setText("Agregar");
        jButtonAgregarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarConsultasActionPerformed(evt);
            }
        });

        jButtonEliminarConsultas.setText("Eliminar");
        jButtonEliminarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarConsultasActionPerformed(evt);
            }
        });

        jLabel9.setText("Ordenar datos");

        jLabel10.setText("Atributo");

        jComboBoxAtributosOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Orden");

        jRadioButtonAsendente.setText("Asendente");
        jRadioButtonAsendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAsendenteActionPerformed(evt);
            }
        });

        jRadioButtonDesendente.setText("Desendente");
        jRadioButtonDesendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDesendenteActionPerformed(evt);
            }
        });

        jRadioButtonNinguno.setText("Ninguno");
        jRadioButtonNinguno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNingunoActionPerformed(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        jButtonAgregarCondiciones.setText("Agregar");
        jButtonAgregarCondiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarCondicionesActionPerformed(evt);
            }
        });

        jLabel12.setText("Condiciones de la consulta");

        jLabel13.setText("6. Condicion");

        jComboBoxCondicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "AND", "OR" }));
        jComboBoxCondicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCondicionActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(listCondicionCon);

        jButton1.setText("REMOVER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBoxOperacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTabla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(56, 56, 56)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4)
                                        .addComponent(jComboBoxOperador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jComboBoxAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonAgregarCondiciones)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxAtributosOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonAsendente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonDesendente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonNinguno))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel6))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButtonAgregarConsultas)
                                                        .addGap(5, 5, 5)
                                                        .addComponent(jButtonEliminarConsultas))
                                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButtonAgregarAtributos)
                                                    .addComponent(jButtonEliminarAtributos)))
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jScrollPaneMuestraTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jButtonAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalir)))
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxOperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(jComboBoxCondicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAgregarCondiciones)
                            .addComponent(jButton1))))
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jButtonAgregarAtributos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEliminarAtributos)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAgregarConsultas)
                            .addComponent(jButtonEliminarConsultas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addComponent(jScrollPaneMuestraTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxAtributosOrdenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jRadioButtonAsendente)
                    .addComponent(jRadioButtonDesendente)
                    .addComponent(jRadioButtonNinguno))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
         /**
      * En nombreTabla se guarda la seleccion de las tablas 
      * mostradas en el comobobox Tabla se recive <>
      * 
      * 
      */
        ArrayList<String> nombretablas;
         nombretablas = new ArrayList();
         nombretablas.add(jComboBoxTabla.getSelectedItem().toString());
         ArrayList<ArrayList<String>> registros;
       if(nombretablas.isEmpty()  || this.jTextArea3.getText().length()==0){
            JOptionPane.showMessageDialog(rootPane, "No se ha seleccionado ninguna atributos", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
        else{
           
              /**
      * Case para la selecion del comobox Operaciones
      * con dos opciones , SELECT y DELETE 
      * 
      * 
      */
            
            switch (this.jComboBoxOperacion.getSelectedItem().toString()) {

                /**
                 * en ls opcion SELECT se activa el radio Button => ContarRB
                 *
                 *
                 */
                case "select": {
                    try {
                        if (this.jComboBoxAtributosOrdenar.getSelectedItem().equals("Ningún atributo")) {

                            
                                registros = (ArrayList<ArrayList<String>>) NEGOCIO_OBJETOS.getInstance().obtenerRegistros(nombretablas, attSeleccionados, this.condSeleccionados, null, null);
                                funciones.clear();
                            
                            
                            if(registros.isEmpty()){
                              JOptionPane.showMessageDialog(rootPane, "Lo requerido No existe", "Aviso", JOptionPane.ERROR_MESSAGE);
                              return;
                            }
                            

                        } else {

                            ArrayList<String> order = new ArrayList();
                            order.add(this.jComboBoxAtributosOrdenar.getSelectedItem().toString());
                            if (this.jRadioButtonAsendente.isSelected()) {
                                order.add("ASC");
                            } else if (this.jRadioButtonDesendente.isSelected()) {
                                order.add("DESC");
                            } else {
                                order.add("");
                            }

                            registros = (ArrayList<ArrayList<String>>) NEGOCIO_OBJETOS.getInstance().obtenerRegistros(nombretablas, this.attSeleccionados, this.condSeleccionados, this.funciones, order);

                        }

                        this.mostrarTabla(registros);
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Aviso", JOptionPane.ERROR_MESSAGE);
                    }
                    break;
                }// finaliza  case SELECT 

           
       }
                       // this.ContarRB.setVisible(true);
                        this.jTextFieldValor.setText("");
                        this.jList1.setEnabled(true);
                        this.jList2.setEnabled(true); 
       } 
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonAgregarAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarAtributosActionPerformed
        // TODO add your handling code here:
        String nombre = this.jList1.getModel().getElementAt(this.jList1.getSelectedIndex());
        if(!this.attSeleccionados.contains(nombre) ){
            this.attSeleccionados.add(nombre);
            DefaultListModel model = new DefaultListModel();
            for(int i=0; i<attSeleccionados.size(); i++){
                model.addElement(attSeleccionados.get(i));
            }
            this.jList2.setModel(model);
        }
        
    }//GEN-LAST:event_jButtonAgregarAtributosActionPerformed

    private void jButtonEliminarAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarAtributosActionPerformed
        // TODO add your handling code here:
         String nombre = this.jList1.getModel().getElementAt(this.jList1.getSelectedIndex());
        this.attSeleccionados.remove(nombre);
        DefaultListModel model = new DefaultListModel();
        for(int i=0; i<attSeleccionados.size(); i++){
            model.addElement(attSeleccionados.get(i));
        }
        this.jList2.setModel(model);
        
    }//GEN-LAST:event_jButtonEliminarAtributosActionPerformed

    private void jComboBoxTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTablaActionPerformed
        // TODO add your handling code here:
        this.jComboBoxAtributo.removeAllItems();
          this.condSeleccionados = new ArrayList();
          this.attSeleccionados = new ArrayList();
         this.jList2.setModel(new DefaultListModel());
         //this.listCondicion.setModel(new DefaultListModel());
         if(!this.jComboBoxTabla.getSelectedItem().toString().isEmpty()){
            try {
                ArrayList<String> atributos = (ArrayList<String>) NEGOCIO_OBJETOS.getInstance().getAtributosTabla(this.jComboBoxTabla.getSelectedItem().toString());
                DefaultListModel model = new DefaultListModel();
                this.jComboBoxAtributo.addItem("Ningún atributo");
                this.jComboBoxAtributosOrdenar.removeAllItems();
                this.jComboBoxAtributosOrdenar.addItem("Ningún atributo");
                
                for(int i=0; i<atributos.size(); i++){
                    model.addElement(atributos.get(i));
                    this.jComboBoxAtributo.addItem(atributos.get(i));
                    this.jComboBoxAtributosOrdenar.addItem(atributos.get(i));
                    
                }
                this.jList1.setModel(model);
                this.jButtonAgregarAtributos.setEnabled(false);
                this.jButtonEliminarAtributos.setEnabled(false);
                //this.btnAgregar1.setEnabled(false);
                //this.btnQuitar1.setEnabled(false);
                this.jButtonAceptar.setVisible(true);
                //this.btnAgregar1.setEnabled(false);
            } catch (Exception ex) {
                Logger.getLogger(Select.class.getName()).log(Level.SEVERE, null, ex);
            }
         
            }
            else{
               
            }// fin else hasta aqui copiar 
    }//GEN-LAST:event_jComboBoxTablaActionPerformed

    private void jRadioButtonAsendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAsendenteActionPerformed
        // TODO add your handling code here:
         if (jRadioButtonDesendente.isSelected() || jRadioButtonNinguno.isSelected()){
            jRadioButtonDesendente.setSelected(false);
            jRadioButtonNinguno.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonAsendenteActionPerformed

    private void jRadioButtonNingunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNingunoActionPerformed
        // TODO add your handling code here:
         if (jRadioButtonAsendente.isSelected() || jRadioButtonDesendente.isSelected()){
            jRadioButtonAsendente.setSelected(false);
            jRadioButtonDesendente.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonNingunoActionPerformed

    private void jRadioButtonDesendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDesendenteActionPerformed
        // TODO add your handling code here:
           if (jRadioButtonAsendente.isSelected() || jRadioButtonNinguno.isSelected()){
            jRadioButtonAsendente.setSelected(false);
             jRadioButtonNinguno.setSelected(false);
        }
    }//GEN-LAST:event_jRadioButtonDesendenteActionPerformed

    private void jButtonAgregarCondicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarCondicionesActionPerformed
        // TODO add your handling code here:
         if(this.jTextFieldValor.getText().length()==0 ||  jComboBoxAtributo.getSelectedItem().equals("Ningún atributo")){
            
              JOptionPane.showMessageDialog(rootPane, "Campos Vacios", "Aviso", JOptionPane.ERROR_MESSAGE);
        }else{
         if(this.jComboBoxOperador.getSelectedItem().equals("LIKE")){
             String name = jComboBoxCondicion.getSelectedItem()+" "+this. jComboBoxAtributo.getSelectedItem()+"  "+ this.jComboBoxOperador.getSelectedItem() + "  '" + this.jTextFieldValor.getText() +"%"+ "' ";
             this.condSeleccionados.add(name);
             jTextArea3.append(name);
             //System.out.println(""+condGenerada);
              jButtonAgregarAtributos.setEnabled(true);
         jButtonEliminarAtributos.setEnabled(true);
          jTextFieldValor.setText("");
         } else if(!this.jComboBoxOperador.getSelectedItem().equals("LIKE")){
            
              
               jComboBoxCondicion.setEnabled(true);
        String miatributo ="'"+jTextFieldValor.getText()+"'";
        jTextArea3.append(jComboBoxCondicion.getSelectedItem()+" "+jComboBoxAtributo.getSelectedItem()+""
                +jComboBoxOperador.getSelectedItem()+miatributo+"  ");
         
         jButtonAgregarAtributos.setEnabled(true);
         jButtonEliminarAtributos.setEnabled(true);
         this.condSeleccionados.add(jComboBoxCondicion.getSelectedItem()+" "+jComboBoxAtributo.getSelectedItem()+""+jComboBoxOperador.getSelectedItem()+miatributo);
         jTextFieldValor.setText("");
        }
       
         }
    }//GEN-LAST:event_jButtonAgregarCondicionesActionPerformed

    private void jComboBoxCondicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCondicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCondicionActionPerformed

    private void jComboBoxOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOperacionActionPerformed
        // TODO add your handling code here:
        jButtonAgregarAtributos.setEnabled(true);
        jButtonEliminarAtributos.setEnabled(true);
    }//GEN-LAST:event_jComboBoxOperacionActionPerformed

    private void jButtonAgregarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarConsultasActionPerformed
        // TODO add your handling code here:
        String nombre = this.jComboBoxAtributo.getSelectedItem().toString();
//        if(this.condSeleccionados.contains(nombre)){
//            JOptionPane.showMessageDialog(rootPane, "Ese atributo ya se ha seleccionado", "Aviso", JOptionPane.ERROR_MESSAGE);
//        }
//        else if(this.jComboBoxOperador.getSelectedItem().toString().isEmpty()){
//            JOptionPane.showMessageDialog(rootPane, "Se debe escoger un condicional", "Aviso", JOptionPane.ERROR_MESSAGE);
//        }
//        else if(this.jTextFieldValor.getText().isEmpty()){
//            JOptionPane.showMessageDialog(rootPane, "Se debe especificar un valor para la condicion", "Aviso", JOptionPane.ERROR_MESSAGE);
//        }
//        else if(this.jComboBoxAtributo.getSelectedItem().equals("Ningún atributo")){
//            JOptionPane.showMessageDialog(rootPane, "Se debe escoger un atributo", "Aviso", JOptionPane.ERROR_MESSAGE);
//        }
        //else{
            String condGenerada="";
            if(this.jComboBoxOperador.getSelectedItem().equals("LIKE")){
                condGenerada = nombre +" "+ this.jComboBoxOperador.getSelectedItem()
            + " '" + this.jTextFieldValor.getText() +"%"+ "'";
                System.out.println(""+condGenerada);}
          //  }else{
             //condGenerada = nombre +" "+ this.condicionCondicion.getSelectedItem()
            //+ " '" + this.valorCondicion.getText() + "'";
              System.out.println(""+this.jTextArea3.getText());
               this.condSeleccionados1.add("SELECCIONAR "+this.attSeleccionados+" DONDE "+this.jTextArea3.getText());
           // }
            
           //this.condSeleccionados.add(condGenerada);
            System.out.println("Entra a agrgar  "+this.condSeleccionados.toString());
            DefaultListModel model = new DefaultListModel();
            for(int i=0; i<condSeleccionados1.size(); i++){
                model.addElement(this.condSeleccionados1.get(i));
            }
            this.listCondicionCon.setModel(model);
            
        // condicion generada
    }//GEN-LAST:event_jButtonAgregarConsultasActionPerformed
    
    private void jButtonEliminarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarConsultasActionPerformed
        // TODO add your handling code here:
        String nombre = this.listCondicionCon.getModel().getElementAt(this.listCondicionCon.getSelectedIndex());
       if(this.condSeleccionados1.size()!=0){
            this.condSeleccionados1.remove(nombre);
        DefaultListModel model = new DefaultListModel();
        for(int i=0; i<condSeleccionados1.size(); i++){
            model.addElement(condSeleccionados1.get(i));
        }
        this.listCondicionCon.setModel(model);
       }
       
    }//GEN-LAST:event_jButtonEliminarConsultasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.jTextArea3.setText("");
        this.condSeleccionados.clear();
    }//GEN-LAST:event_jButton1ActionPerformed
    
     private void mostrarTabla(ArrayList<ArrayList<String>> registros) {
        int filas = registros.size()-1;
        int columnas = registros.get(0).size();

        String cuerpo[][] = new String[filas][columnas];
        String cabecera[] = new String[columnas];

        //Cabecera de la tabla
        for (int i = 0; i<columnas; i++){
            cabecera[i] = registros.get(0).get(i);
        }
        //Cuerpo de la tabla
        for (int i = 0; i<filas; i++)
            for (int j = 0; j<columnas; j++)
                cuerpo[i][j] = registros.get(i+1).get(j);

        //Creacion de la tabla 
        JTable table = new JTable(cuerpo, cabecera); 
        table.setPreferredScrollableViewportSize(new Dimension(filas, columnas));

        this.jScrollPaneMuestraTabla.setViewportView(new JTable(cuerpo, cabecera));
    }// fin 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Select.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Select().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonAgregarAtributos;
    private javax.swing.JButton jButtonAgregarCondiciones;
    private javax.swing.JButton jButtonAgregarConsultas;
    private javax.swing.JButton jButtonEliminarAtributos;
    private javax.swing.JButton jButtonEliminarConsultas;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxAtributo;
    private javax.swing.JComboBox<String> jComboBoxAtributosOrdenar;
    private javax.swing.JComboBox<String> jComboBoxCondicion;
    private javax.swing.JComboBox<String> jComboBoxOperacion;
    private javax.swing.JComboBox<String> jComboBoxOperador;
    private javax.swing.JComboBox<String> jComboBoxTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JRadioButton jRadioButtonAsendente;
    private javax.swing.JRadioButton jRadioButtonDesendente;
    private javax.swing.JRadioButton jRadioButtonNinguno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPaneMuestraTabla;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextFieldValor;
    private javax.swing.JList<String> listCondicionCon;
    // End of variables declaration//GEN-END:variables
}
