/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Negocio.NEGOCIO_OBJETOS;
//import com.encuestas.ec.bo.ManejoDatos;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author danny
 */
public class UnionNatural extends javax.swing.JFrame {
    
    
      ArrayList<String> attSeleccionados;
      ArrayList<String> condSeleccionados;
    /**
     * Creates new form UnionNatural
     */
    public UnionNatural() {
        try {
            attSeleccionados = new ArrayList();
            condSeleccionados = new ArrayList();
            initComponents();
            
            ArrayList<String> nombres  = NEGOCIO_OBJETOS.getInstance().getNombresTablas();
            jComboBoxTabla1.addItem("ninguna tabla");
            jComboBoxTabla2.addItem("ninguna tabla");
            jComboBoxTabla3.addItem("ninguna tabla");
            for(int i = 0; i<nombres.size(); i++){
                this.jComboBoxTabla1.addItem(nombres.get(i));
                this.jComboBoxTabla2.addItem(nombres.get(i));
                this.jComboBoxTabla3.addItem(nombres.get(i));
            }
        } catch (Exception ex) {
            Logger.getLogger(UnionNatural.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTabla1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTabla2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListProyectar = new javax.swing.JList<>();
        jButtonAT1 = new javax.swing.JButton();
        jComboBoxTabla1 = new javax.swing.JComboBox<>();
        jComboBoxTabla2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonAT2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        JPV = new javax.swing.JScrollPane();
        jComboBoxTabla3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListTabla3 = new javax.swing.JList<>();
        jButtonAT3 = new javax.swing.JButton();
        jButtonAtributoClave1 = new javax.swing.JButton();
        jButtonAtributoClave2 = new javax.swing.JButton();
        jButtonAtributoClave3 = new javax.swing.JButton();
        jComboBoxTabla5 = new javax.swing.JComboBox<>();
        jTextFieldVal = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabelattr = new javax.swing.JLabel();
        jButtonAgregarAttrSelec = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListAttrSelec = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Union Natural");

        jScrollPane1.setViewportView(jListTabla1);

        jScrollPane2.setViewportView(jListTabla2);

        jScrollPane3.setViewportView(jListProyectar);

        jButtonAT1.setText(">>");
        jButtonAT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAT1ActionPerformed(evt);
            }
        });

        jComboBoxTabla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTabla1ActionPerformed(evt);
            }
        });

        jComboBoxTabla2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTabla2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tabla       Campo");

        jLabel3.setText("Tabla       Campo");

        jLabel4.setText("Proyeccion Join");

        jButtonAT2.setText(">>");
        jButtonAT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAT2ActionPerformed(evt);
            }
        });

        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBoxTabla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTabla3ActionPerformed(evt);
            }
        });

        jLabel5.setText("Tabla       Campo");

        jScrollPane4.setViewportView(jListTabla3);

        jButtonAT3.setText(">>");
        jButtonAT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAT3ActionPerformed(evt);
            }
        });

        jButtonAtributoClave1.setText("Agregar Campo Clave");
        jButtonAtributoClave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtributoClave1ActionPerformed(evt);
            }
        });

        jButtonAtributoClave2.setText("Agregar Campo Clave");
        jButtonAtributoClave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtributoClave2ActionPerformed(evt);
            }
        });

        jButtonAtributoClave3.setText("Agregar Campo Clave");
        jButtonAtributoClave3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtributoClave3ActionPerformed(evt);
            }
        });

        jComboBoxTabla5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTabla5ActionPerformed(evt);
            }
        });

        jButton3.setText("Quitar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonAgregarAttrSelec.setText("Agregar");
        jButtonAgregarAttrSelec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarAttrSelecActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(jListAttrSelec);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(344, 344, 344))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JPV, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTabla1, 0, 204, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(jButtonAT1)
                            .addComponent(jButtonAtributoClave1)
                            .addComponent(jButton3)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelattr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTabla5, 0, 198, Short.MAX_VALUE))
                                .addGap(6, 6, 6)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxTabla2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxTabla3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAT2)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAtributoClave2)
                                    .addComponent(jTextFieldVal, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAgregarAttrSelec))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                    .addComponent(jButtonAT3)
                                    .addComponent(jButtonAtributoClave3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTabla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTabla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxTabla3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAT1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAtributoClave1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAT2)
                            .addComponent(jButtonAT3)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAtributoClave2)
                            .addComponent(jButtonAtributoClave3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jComboBoxTabla5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelattr, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(3, 3, 3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton3)
                                        .addComponent(jButtonAgregarAttrSelec)))
                                .addComponent(jTextFieldVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(JPV, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTabla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTabla1ActionPerformed
        // TODO add your handling code here:
        
        if(!this.jComboBoxTabla1.getSelectedItem().toString().isEmpty()){
            try {
                ArrayList<String> atributos = (ArrayList<String>) NEGOCIO_OBJETOS.getInstance().getAtributosTabla(this.jComboBoxTabla1.getSelectedItem().toString());
                DefaultListModel model = new DefaultListModel();
                
                
                for(int i=0; i<atributos.size(); i++){
                    model.addElement(this.jComboBoxTabla1.getSelectedItem().toString()+"."+atributos.get(i));
                    //this.condicionAtributos.addItem(atributos.get(i));
                    //this.orderAtributo.addItem(atributos.get(i));
                    
                }
                
                this.jListTabla1.setModel(model);
            } catch (Exception ex) {
                Logger.getLogger(UnionNatural.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
    }//GEN-LAST:event_jComboBoxTabla1ActionPerformed

    private void jComboBoxTabla2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTabla2ActionPerformed
        // TODO add your handling code here:
         if(!this.jComboBoxTabla2.getSelectedItem().toString().isEmpty()){
            try {
                ArrayList<String> atributos = (ArrayList<String>) NEGOCIO_OBJETOS.getInstance().getAtributosTabla(this.jComboBoxTabla2.getSelectedItem().toString());
                DefaultListModel model = new DefaultListModel();
                
                
                for(int i=0; i<atributos.size(); i++){
                    model.addElement(this.jComboBoxTabla2.getSelectedItem().toString()+"."+atributos.get(i));
                    //this.condicionAtributos.addItem(atributos.get(i));
                    //this.orderAtributo.addItem(atributos.get(i));
                    
                }
                
                this.jListTabla2.setModel(model);
            } catch (Exception ex) {
                Logger.getLogger(UnionNatural.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
        
    }//GEN-LAST:event_jComboBoxTabla2ActionPerformed

    private void jButtonAT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAT1ActionPerformed
        // TODO add your handling code here:
         String nombre = this.jListTabla1.getModel().getElementAt(this.jListTabla1.getSelectedIndex());
        if(!this.attSeleccionados.contains(nombre) ){
            this.attSeleccionados.add(nombre);
            DefaultListModel model = new DefaultListModel();
            for(int i=0; i<attSeleccionados.size(); i++){
                model.addElement(attSeleccionados.get(i));
            }
            this.jListProyectar.setModel(model);
        }
        
    }//GEN-LAST:event_jButtonAT1ActionPerformed

    private void jButtonAT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAT2ActionPerformed
        // TODO add your handling code here:
         String nombre = this.jListTabla2.getModel().getElementAt(this.jListTabla2.getSelectedIndex());
        if(!this.attSeleccionados.contains(nombre) ){
            this.attSeleccionados.add(nombre);
            DefaultListModel model = new DefaultListModel();
            for(int i=0; i<attSeleccionados.size(); i++){
                model.addElement(attSeleccionados.get(i));
            }
            this.jListProyectar.setModel(model);
        }
    }//GEN-LAST:event_jButtonAT2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String nombre = this.jListProyectar.getModel().getElementAt(this.jListProyectar.getSelectedIndex());
        this.attSeleccionados.remove(nombre);
        DefaultListModel model = new DefaultListModel();
        for(int i=0; i<attSeleccionados.size(); i++){
            model.addElement(attSeleccionados.get(i));
        }
        this.jListProyectar.setModel(model);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mostrarTabla(ArrayList<ArrayList<String>> registros) {
        int filas = registros.size()-1;
        int columnas = registros.get(0).size();

        String cuerpo[][] = new String[filas][columnas];
        String cabecera[] = new String[columnas];

        //Cabecera de la tabla
        for (int i = 0; i<columnas; i++){
            cabecera[i] = registros.get(0).get(i);
        }
        //Cuerpo de la tabla
        for (int i = 0; i<filas; i++)
            for (int j = 0; j<columnas; j++)
                cuerpo[i][j] = registros.get(i+1).get(j);

        //Creacion de la tabla 
        JTable table = new JTable(cuerpo, cabecera); 
        table.setPreferredScrollableViewportSize(new Dimension(filas, columnas));

        this.JPV.setViewportView(new JTable(cuerpo, cabecera));
    }// fin de metodo mostrar tabla 
     
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          try {
              // TODO add your handling code here:
              ArrayList<String> nombretablas;
              nombretablas = new ArrayList();
              if(this.jComboBoxTabla1.getSelectedItem().equals("ninguna tabla")){
              
              }else{
               nombretablas.add(this.jComboBoxTabla1.getSelectedItem().toString());
              }
              
              if(this.jComboBoxTabla2.getSelectedItem().equals("ninguna tabla")){
              
              }else{
               nombretablas.add(this.jComboBoxTabla2.getSelectedItem().toString());
              }
              
              if(this.jComboBoxTabla3.getSelectedItem().equals("ninguna tabla")){
              
              }else{
               nombretablas.add(this.jComboBoxTabla3.getSelectedItem().toString());
              }
              
              ArrayList<ArrayList<String>> registros;
              registros = (ArrayList<ArrayList<String>>) NEGOCIO_OBJETOS.getInstance().obtenerRegistrosJoin(nombretablas,this.attSeleccionados,this.condSeleccionados,null, null);
              this.mostrarTabla(registros);
          } catch (Exception ex) {
              Logger.getLogger(UnionNatural.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxTabla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTabla3ActionPerformed
        // TODO add your handling code here:
        
            if(!this.jComboBoxTabla3.getSelectedItem().toString().isEmpty()){
            try {
                ArrayList<String> atributos = (ArrayList<String>) NEGOCIO_OBJETOS.getInstance().getAtributosTabla(this.jComboBoxTabla2.getSelectedItem().toString());
                DefaultListModel model = new DefaultListModel();
                
                
                for(int i=0; i<atributos.size(); i++){
                    model.addElement(this.jComboBoxTabla3.getSelectedItem().toString()+"."+atributos.get(i));
                    //this.condicionAtributos.addItem(atributos.get(i));
                    //this.orderAtributo.addItem(atributos.get(i));
                    
                }
                
                this.jListTabla3.setModel(model);
            } catch (Exception ex) {
                Logger.getLogger(UnionNatural.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
        
    }//GEN-LAST:event_jComboBoxTabla3ActionPerformed

    private void jButtonAT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAT3ActionPerformed
        // TODO add your handling code here:
        String nombre = this.jListTabla3.getModel().getElementAt(this.jListTabla3.getSelectedIndex());
        if(!this.attSeleccionados.contains(nombre) ){
            this.attSeleccionados.add(nombre);
            DefaultListModel model = new DefaultListModel();
            for(int i=0; i<attSeleccionados.size(); i++){
                model.addElement(attSeleccionados.get(i));
            }
            this.jListProyectar.setModel(model);
        }
    }//GEN-LAST:event_jButtonAT3ActionPerformed

    private void jButtonAtributoClave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtributoClave1ActionPerformed
        // TODO add your handling code here:
         String nombre = this.jListTabla1.getModel().getElementAt(this.jListTabla1.getSelectedIndex());
         this.jComboBoxTabla5.addItem(nombre);
      
    }//GEN-LAST:event_jButtonAtributoClave1ActionPerformed

    private void jComboBoxTabla5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTabla5ActionPerformed
        // TODO add your handling code here:
           if(!this.jComboBoxTabla5.getSelectedItem().toString().isEmpty()){
            this.jLabelattr.setText(jComboBoxTabla5.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBoxTabla5ActionPerformed

    private void jButtonAtributoClave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtributoClave2ActionPerformed
        // TODO add your handling code here:
         String nombre = this.jListTabla2.getModel().getElementAt(this.jListTabla2.getSelectedIndex());
         this.jComboBoxTabla5.addItem(nombre);
    }//GEN-LAST:event_jButtonAtributoClave2ActionPerformed

    private void jButtonAtributoClave3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtributoClave3ActionPerformed
        // TODO add your handling code here:
         String nombre = this.jListTabla3.getModel().getElementAt(this.jListTabla3.getSelectedIndex());
         this.jComboBoxTabla5.addItem(nombre);
    }//GEN-LAST:event_jButtonAtributoClave3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(!this.jComboBoxTabla5.getSelectedItem().toString().isEmpty()){
            this.jComboBoxTabla5.removeAllItems();
        }
        this.jLabelattr.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonAgregarAttrSelecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarAttrSelecActionPerformed
        // TODO add your handling code here:
        String atributo  = this.jComboBoxTabla5.getSelectedItem().toString();
        String valor  = this.jTextFieldVal.getText();
        String condicion = atributo +""+"="+""+valor;
    
         this.condSeleccionados.add(condicion);
         DefaultListModel model = new DefaultListModel();
         //model.addElement(condicion);
           for(int i=0; i<condSeleccionados.size(); i++){
                model.addElement(condSeleccionados.get(i));
            }
            this.jListAttrSelec.setModel(model);
        
    }//GEN-LAST:event_jButtonAgregarAttrSelecActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnionNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnionNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnionNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnionNatural.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnionNatural().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JPV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAT1;
    private javax.swing.JButton jButtonAT2;
    private javax.swing.JButton jButtonAT3;
    private javax.swing.JButton jButtonAgregarAttrSelec;
    private javax.swing.JButton jButtonAtributoClave1;
    private javax.swing.JButton jButtonAtributoClave2;
    private javax.swing.JButton jButtonAtributoClave3;
    private javax.swing.JComboBox<String> jComboBoxTabla1;
    private javax.swing.JComboBox<String> jComboBoxTabla2;
    private javax.swing.JComboBox<String> jComboBoxTabla3;
    private javax.swing.JComboBox<String> jComboBoxTabla5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelattr;
    private javax.swing.JList<String> jListAttrSelec;
    private javax.swing.JList<String> jListProyectar;
    private javax.swing.JList<String> jListTabla1;
    private javax.swing.JList<String> jListTabla2;
    private javax.swing.JList<String> jListTabla3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextFieldVal;
    // End of variables declaration//GEN-END:variables
}
